ppw_app/urls.py
from django.urls import path
from . import views

app_name = 'ppw_app'
urlpatterns = [
	path('', views.home_view, name="home_url"),
	path('profile', views.profile_view, name="profile_url"),
	path('form/tambah', views.uploadMatkul, name="form_url"),
	path('form', views.index, name="index_url"),
	path('delete/<int:kode>', views.deleteMatkul, name="delete_url"),
]

ppw_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ppw_app.urls')),
    path('', include('story7.urls')),
     path('', include('story8.urls')),
]

story7/urls.py
from django.urls import path
from . import views

app_name = 'story7'
urlpatterns = [
	path('story7', views.story7, name="story7"),
]

story8/urls.py
from django.urls import path
from . import views

app_name = 'story8'
urlpatterns = [
	path('story8', views.story8, name="story8"),
    path('result/', views.result, name="result"),
]

story9/urls.py
from django.urls import path
from . import views

app_name = 'story7'
urlpatterns = [
	path('story7', views.story7, name="story7"),
]

ppw_app/models.py
from django.db import models

class daftarMatkul(models.Model):
	daftarSemester = (('Gasal 2019/2020', 'Gasal 2019/2020'),
		('Genap 2019/2020', 'Genap 2019/2020'), ('Gasal 2020/2021', 'Gasal 2020/2021'),
		('Genap 2020/2021', 'Genap 2020/2021'), ('Gasal 2021/2022', 'Gasal 2021/2022'),
		('Genap 2021/2022', 'Genap 2021/2022'), ('Gasal 2022/2023', 'Gasal 2022/2023'))
	mataKuliah = models.CharField(max_length = 50)
	namaDosen = models.CharField(max_length = 50)
	jumlahSKS = models.PositiveIntegerField(null = True)
	deskripsi = models.TextField(max_length = 50)
	semesterTahun = models.CharField(max_length = 50, choices = daftarSemester, null = True)
	ruangKelas = models.CharField(max_length = 50)

	def __str__(self):
		return self.mataKuliah

story7/models.py
from django.db import models

# Create your models here.

story8/models.py
from django.db import models

# Create your models here.

story9/models.py
from django.db import models

# Create your models here.

ppw_app/forms.py
from django import forms
from .models import daftarMatkul

class createMatkul(forms.ModelForm):
	class Meta:
		model = daftarMatkul
		fields = '__all__'

ppw_app/views.py
from django.shortcuts import redirect, render
from .forms import createMatkul
from .models import daftarMatkul
from django.http import HttpResponse, HttpResponseRedirect

def index(request):
	listMatkul = daftarMatkul.objects.all()
	return render(request, 'daftar.html', {'Daftar' : listMatkul})

def uploadMatkul(request):
	upload = createMatkul()
	if (request.method == 'POST'):
		upload = createMatkul(request.POST, request.FILES)
		if (upload.is_valid()):
			upload.save()
			return HttpResponseRedirect('/form')
	else:
		return render(request, 'form.html', {'upload_form' : upload})

def deleteMatkul(request, kode):
	mataKuliah = daftarMatkul.objects.get(id = kode)
	print(mataKuliah)
	mataKuliah.delete()
	return redirect('/form')

def home_view(request):
	return render(request, "home.html")

def profile_view(request):
	return render(request, "profile.html")

story7/views.py
from django.shortcuts import render

# Create your views here.

def story7(request):
    return render(request,'story7.html')

story8/views.py
from django.shortcuts import redirect, render
from django.http import JsonResponse
import requests
import  json

# Create your views here.

def story8(request):
    return render (request, 'story8.html')

def result(request):
    url = "https://www.googleapis.com/books/v1/volumes?q=" + request.GET.get('q','frozen')
    ret = requests.get(url)
    data= json.loads(ret.content)
    return JsonResponse(data, safe=False)

story9/views.py
from django.shortcuts import render

# Create your views here.

def story7(request):
    return render(request,'story7.html')

ppw_app/templates/daftar.html
{% extends 'base.html' %} {% load static %} {% block meta %}

<title> Mata Kuliah </title>
<link rel="stylesheet" href="{% static 'css/profile.css' %}" />
<!-- head closed-->
{% endblock meta %} {% block content %}

<section id="baseukuran" class="daftar-section">
    <div class="container">
        <table class="table" border="1px">
            <thead>
                <tr>
                    <th scope="col">Mata Kuliah</th>
                    <th scope="col">Nama Dosen</th>
                    <th scope="col">Jumlah SKS</th>
                    <th scope="col">Semester Tahun</th>
                    <th scope="col">Hapus Mata Kuliah</th>
                </tr>
            </thead>
            <tbody>
                {% if Daftar %} {% for course in Daftar %}
                <tr>
                    <td>{{course.mataKuliah}}</td>
                    <td>{{course.namaDosen}}</td>
                    <td>{{course.jumlahSKS}}</td>
                    <td>{{course.semesterTahun}}</td>
                    <td>
                        <a href="{% url 'ppw_app:delete_url' course.id %}" class="btn btn-primary">
                            Hapus
                        </a>
                    </td>
                </tr>
                {% endfor %}{% endif %}
            </tbody>
        </table>
        <a href="/form/tambah" type="submit" class="btn btn-primary">Tambah</a>
    </div>
</section>
{% endblock content %}

ppw_app/templates/form.html
{% extends 'base.html' %} {% load static %} {% block meta %}

<title>Form Mata Kuliah</title>
<link rel="stylesheet" href="{% static 'css/profile.css' %}" />
<!-- Title End-->

{% endblock meta %} {% block content %}
<section class="form-section" id="baseukuran">
    <div class="container">
        <form action="" method="POST">
            {% csrf_token %}
            <h1 class="nama"> Mata Kuliah: {{ upload_form.mataKuliah }} </h1> <br>
            <h1 class="npm"> Nama Dosen: {{ upload_form.namaDosen }} </h1> <br>
            <h1 class="hobi"> Jumlah SKS: {{ upload_form.jumlahSKS }} </h1> <br>
            <h1 class="deskripsi"> Deskripsi Mata Kuliah: {{ upload_form.deskripsi }} </h1> <br>
            <h1 class="universitas"> Semester Tahun: {{ upload_form.semesterTahun }} </h1> <br>
            <h1 class="pendidikan"> Kode Ruang Kelas: {{ upload_form.ruangKelas }} </h1> <br>
            <button type="submit" class="btn btn-primary"><h4>Submit</h4></button>
        </form>
    </div>
</section>
{% endblock content %}

ppw_app/templates/home.html
{% extends 'base.html' %} {% load static %} {% block meta %}
<link rel="stylesheet" href="{% static 'css/profile.css' %}" />
<title>Halaman Profil Saya</title>

{% endblock meta %} {% block content %}
<section class="home-section">
    <div class="container">
        <h1 class="nama">Halo, nama saya Julian Fernando</h1>
        <h1 class="npm">NPM 1906285522</h1>
        <h1 class="angkatan">Angkatan 2019</h1>
        <h1 class="hobi">Saya hobi berenang, bersepeda, dan bermain gitar</h1>
        <h1 class="deskripsi">Mengenai saya, saya adalah seseorang yang cukup humoris dan mudah diajak bercanda</h1>
        <h1 class="universitas">Saat ini, saya berkuliah di Universitas Indonesia</h1>
        <h1 class="pendidikan">Riwayat pendidikan saya antara lain:</h1>
        <table class="table pendidikan tabel" style="width:75%">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Jenjang</th>
                    <th scope="col"> Nama Sekolah </th>
                    <th scope="col"> Tahun </th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Taman Kanak</td>
                    <td>TK Xaverius 1 Kota Jambi</td>
                    <td>2005 - 2007</td>
                </tr>
                <tr>
                    <td>Sekolah Dasar</td>
                    <td>SD Xaverius 1 Kota Jambi</td>
                    <td>2007 - 2013</td>
                </tr>
                <tr>
                    <td>Sekolah Menengah Pertama</td>
                    <td>SMP Xaverius 1 Kota Jambi</td>
                    <td>2013 - 2016</td>
                </tr>
                <tr>
                    <td>Sekolah Menengah Atas</td>
                    <td>SMA Negeri 3 Kota Jambi</td>
                    <td>2016 - 2019</td>
                </tr>
                <tr>
                    <td>Program Sarjana</td>
                    <td>Universitas Indonesia</td>
                    <td>2019 - sekarang</td>
                </tr>
            </tbody>
        </table>
    </div>
</section>
{% endblock content %}

ppw_app/templates/profile.html
{% extends 'base.html' %} {% load static %} {% block meta %}

<!-- head -->
<title>My Profile</title>
<link rel="stylesheet" href="{% static 'css/profile.css' %}" />
<!-- head -->

<!-- content-->
{% endblock meta %} {% block content %}
<section class="profile-section" id="baseukuran">
    <div class="container">
        <div class="col-lg-12 col-xs-12">
            <div class="title">
                <h1 class="tengah">Welcome to My Profile</h1>
            </div>
        </div>
    </div>
    <div class="container bagian-profile-2">
        <div class="row">
            <div class="col">
                <div class="Informasi1">
                    <h1 class="informasi1-judul">About Me</h1>
                    <p class="def-about"> Saya merupakan seorang yang humoris dan mudah bergaul dengan siapapun.</p>
                    <img class="img-fluid" id="foto" src="{% static 'images/Netco.jpeg' %}" alt="Foto Keren" width="200" height="300">
                </div>
            </div>
            <div class="col">
                <div class="tengah">
                    <h1>Biodata</h1>
                    <div class="tulisan">
                        <h3 class="nama">Nama: Julian Fernando</h3>
                        <h3 class="npm">NPM: 1906285522</h3>
                        <h3 class="angkatan">Angkatan: 2019</h3>
                        <h3 class="universitas">PTN: Universitas Indonesia</h3>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="Informasi2">
                    <h1 class="informasi2-judul">My Hobby</h1>
                    <p class="def-about">Hobi yang saya tekuni ialah Competitive Programming yang berupa kompetisi problem solving dengan memanfaatkan pemrograman.</p>
                    <img class="img-fluid" id="foto" src="{% static 'images/Arkavidia6.0.jpeg' %}" alt="Ngoding Kece" width="200" height="300">
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

story7/templates/story7.html
{% extends 'base.html' %} {% load static %} {% block meta %}

<title>More Info About Me</title>
<link rel="stylesheet" href="{% static 'css/tujuh.css' %}" />
<link rel="stylesheet" href="/resources/demos/style.css">

<script src="{% static 'JS/tujuh.js' %}"></script>
<!-- Title End-->

{% endblock meta %} {% block content %}
<section class="story-section" id="baseukuran">
    <h1 style="text-align: center;">Lebih Lanjut tentang Julian</h1>
    <div class="container">
        <div id="accordion">
            <div class="group">
                <h3> Cita-cita </h3>
                <div>
                    <p>
                        Saya memiliki cita-cita untuk menjadi seorang Software Engineer.
                    </p>
                    <button type="button" class="btn btn-primary up"> UP </button>
                    <button type="button" class="btn btn-primary down"> DOWN </button>
                </div>
            </div>
            <div class="group">
                <h3> Organisasi </h3>
                <div>
                    <ul>
                        <li>Ristek CSUI - Senior Member</li>
                        <li>KMK CSUI - Staf Divisi Acara</li>
                    </ul>
                    <button type="button" class="btn btn-primary up"> UP </button>
                    <button type="button" class="btn btn-primary down"> DOWN </button>
                </div>
            </div>
            <div class="group">
                <h3> Kepanitiaan </h3>
                <div>
                    <ul>
                        <li>Compfest 12 - SC CPC</li>
                        <li>Pekan Ristek 2020 - PJ IPSC 2020</li>
                    </ul>
                    <button type="button" class="btn btn-primary up"> UP </button>
                    <button type="button" class="btn btn-primary down"> DOWN </button>
                </div>
            </div>
            <div class="group">
                <h3> Prestasi </h3>
                <div>
                    <ul>
                        <li>OSN Komputer 2018 - Medali Perunggu</li>
                        <li>ICPC Regional Asia Jakarta - Medali Emas</li>
                        <li>Find It! 2020 - Juara I</li>
                        <li>Gemastik 13 - Honorable Mention (Juara IV)</li>
                        <li>Techphoria 2020 - Juara II</li>
                        <li>Hology 3.0 - Juara I</li>
                    </ul>
                    <button type="button" class="btn btn-primary up"> UP </button>
                    <button type="button" class="btn btn-primary down"> DOWN </button>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

story8/templates/story8.html
{% extends 'base.html' %} {% load static %} {% block meta %}

<title> My AJAX </title>
<link rel="stylesheet" href="{% static 'css/books.css' %}" />

<script src="{% static 'js/books.js' %}"></script>
<!-- Title End-->

{% endblock meta %} {% block content %}
<section class="books-section" id="baseukuran">
    <h1 style="text-align: center;"> Find Book With AJAX </h1>
    <div class="container">
        <input type="text" name="cari" id="cari" placeholder="Cari " class="form-control form-control-lg">
        <br><br>
        <table class="table" id="hasil">

        </table>
    </div>

</section>
{% endblock content %}

story9/templates/story7.html
{% extends 'base.html' %} {% load static %} {% block meta %}

<title>More Info About Me</title>
<link rel="stylesheet" href="{% static 'css/tujuh.css' %}" />
<link rel="stylesheet" href="/resources/demos/style.css">

<script src="{% static 'JS/tujuh.js' %}"></script>
<!-- Title End-->

{% endblock meta %} {% block content %}
<section class="story-section" id="baseukuran">
    <h1 style="text-align: center;">Lebih Lanjut tentang Julian</h1>
    <div class="container">
        <div id="accordion">
            <div class="group">
                <h3> Cita-cita </h3>
                <div>
                    <p>
                        Saya memiliki cita-cita untuk menjadi seorang Software Engineer.
                    </p>
                    <button type="button" class="btn btn-primary up"> UP </button>
                    <button type="button" class="btn btn-primary down"> DOWN </button>
                </div>
            </div>
            <div class="group">
                <h3> Organisasi </h3>
                <div>
                    <ul>
                        <li>Ristek CSUI - Senior Member</li>
                        <li>KMK CSUI - Staf Divisi Acara</li>
                    </ul>
                    <button type="button" class="btn btn-primary up"> UP </button>
                    <button type="button" class="btn btn-primary down"> DOWN </button>
                </div>
            </div>
            <div class="group">
                <h3> Kepanitiaan </h3>
                <div>
                    <ul>
                        <li>Compfest 12 - SC CPC</li>
                        <li>Pekan Ristek 2020 - PJ IPSC 2020</li>
                    </ul>
                    <button type="button" class="btn btn-primary up"> UP </button>
                    <button type="button" class="btn btn-primary down"> DOWN </button>
                </div>
            </div>
            <div class="group">
                <h3> Prestasi </h3>
                <div>
                    <ul>
                        <li>OSN Komputer 2018 - Medali Perunggu</li>
                        <li>ICPC Regional Asia Jakarta - Medali Emas</li>
                        <li>Find It! 2020 - Juara I</li>
                        <li>Gemastik 13 - Honorable Mention (Juara IV)</li>
                        <li>Techphoria 2020 - Juara II</li>
                        <li>Hology 3.0 - Juara I</li>
                    </ul>
                    <button type="button" class="btn btn-primary up"> UP </button>
                    <button type="button" class="btn btn-primary down"> DOWN </button>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    {% block meta %}{% endblock meta %}
</head>

<body>
    <!-- navbar-->
    <nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark">
        <a class="navbar-brand text" href="/" style="">
            <img src="{% static 'images/pas_foto.jpg'%}" width="30" height="30" class="d-inline-block align-top" alt="" loading="lazy"> Home
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link text" href="/profile"> Profile <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link text" href="/form"> Form <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link text" href="/story7"> More Info <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link text" href="/story8"> Search Book <span class="sr-only">(current)</span></a>
                </li>
            </ul>
        </div>
    </nav>
    <section id="baseukuran" style="min-height:800px;">
        {% block content %} {% endblock content %}
    </section>
    <section class="medsos" id="footer">
        <div>
            <h1> Created by Julian </h1>
        </div>
    </section>
</body>

</html>